version: '3.8'

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:7.9.1
    container_name: zookeeper
    restart: on-failure
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - flink_commerce_network

  broker:
    image: confluentinc/cp-server:7.9.1
    container_name: broker
    restart: on-failure
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
      - "29092:29092"
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: "INTERNAL://broker:29092,EXTERNAL://localhost:9092"
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: "INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT"
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
    volumes:
      - kafka_data:/var/lib/kafka
    networks:
      - flink_commerce_network

  control-center:
    image: confluentinc/cp-enterprise-control-center:7.9.1
    container_name: control-center
    ports:
      - "9021:9021"
    restart: on-failure
    depends_on:
      - broker
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: broker:29092
      CONTROL_CENTER_REPLICATION_FACTOR: 1
    networks:
      - flink_commerce_network

  flink-jobmanager:
    image: flink:1.18.1-scala_2.12-java17
    container_name: flink-jobmanager
    ports:
      - "8082:8081"
    command: jobmanager
    restart: on-failure
    environment:
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    volumes:
      - ./src/main/java/FlinkCommerce:/opt/flink/jobs
      - ./target:/opt/flink/target
    networks:
      - flink_commerce_network

  flink-taskmanager:
    image: flink:1.18.1-scala_2.12-java17
    container_name: flink-taskmanager
    command: taskmanager
    restart: on-failure
    depends_on:
      - flink-jobmanager
    environment:
      TASK_MANAGER_NUMBER_OF_TASK_SLOTS: 1
      JOB_MANAGER_RPC_ADDRESS: flink-jobmanager
    networks:
      - flink_commerce_network

  postgres:
    image: postgres:17
    container_name: postgres
    ports:
      - "5432:5432"
    restart: on-failure
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: transaction
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - flink_commerce_network

  elasticsearch:
    image: elasticsearch:8.18.2
    container_name: elasticsearch
    ports:
      - "9200:9200"
    restart: on-failure
    environment:
      discovery.type: single-node
      xpack.security.enabled: false
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
    networks:
      - flink_commerce_network

  kibana:
    image: kibana:8.18.2
    container_name: kibana
    ports:
      - "5601:5601"
    restart: on-failure
    depends_on:
      - elasticsearch
    environment:
      ELASTICSEARCH_HOSTS: http://elasticsearch:9200
    networks:
      - flink_commerce_network

volumes:
  kafka_data:
  elastic_data:
  postgres_data:

networks:
  flink_commerce_network: